#########################################################################
# Title:         Saltbox: Mainline Role                                 #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Install gnupg Dependencies
  ansible.builtin.apt:
    name: dirmngr

- name: Add gpg signing key to trusted.gpg.d
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3AE27527713D2479DCAFFD58A89D7C1B2F76304D
    dest: /etc/apt/trusted.gpg.d/cappelikan.asc
    mode: "0644"
  register: result
  retries: "{{ '0' if (not continuous_integration) else '5' }}"
  delay: 10
  until: result is succeeded

- name: Remove old repository entry
  ansible.builtin.apt_repository:
    repo: "deb [arch=arm64 signed-by=/usr/share/keyrings/cappelikan.gpg] http://ppa.launchpad.net/cappelikan/ppa/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    filename: "cappelikan"
    update_cache: true
    state: absent

- name: Add cappelikan/ppa repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=arm64 signed-by=/etc/apt/trusted.gpg.d/cappelikan.asc] http://ppa.launchpad.net/cappelikan/ppa/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    filename: "cappelikan"
    state: present
    update_cache: true

- name: Install mainline
  ansible.builtin.apt:
    name: mainline
    state: present
